config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }
  # Those three callbacks are equivalent to the following single line
  broadcasts_to ->(quote) { [ quote.company, "quotes" ] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable

  belongs_to :company

  def name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end
  helper_method :current_company
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [ :show, :edit, :update, :destroy ]
  def index
    @quotes = current_company.quotes.ordered
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
<div class="flash__message" data-controller="removals" data-action="animationend->removals#remove">
  <%= message %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
  <div class="navbar__brand">
    <%= current_company.name %>
  </div>
  <div class="navbar__name">
    <%= current_user.name %>
  </div>
  <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
  <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= content_for(:title) || "Quote Editor" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
  <%= render "layouts/navbar" %>

  <div id="flash" class="flash">
    <%= render "layouts/flash" %>
  </div>

  <%= yield %>
</body>

</html>

app/views/pages/home.html.erb
<main class="container">
  <h1>Quote editor</h1>
  <p>A blazing fast quote editor built with Hotwire</p>

  <% if user_signed_in? %>
  <%= link_to "View quotes", quotes_path, class: "btn btn--dark" %>
  <% else %>
  <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</main>

app/views/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>

  <%= link_to "Add quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Quote.new) } %>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form"} do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>
  <%= f.input :name, input_html: { autofocus: true} %>
  <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_new_quote_button.html.erb
<% if quotes.present? %>
  <%= link_to "New quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) }, class: "btn btn--primary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" } %>
    <div class="quote_actions">
      <%= button_to "Delete", quote_path(quote), method: :delete, class: "btn btn--light" %>
      <%= link_to "Edit", edit_quote_path(quote), class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %> 
<%= turbo_stream.update Quote.new, "" %>
<%= turbo_stream.update "new_quote_button", partial: "quotes/new_quote_button", locals: { quotes: current_company.quotes } %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove "quote_#{@quote.id}" %>

<% unless current_company.quotes.exists? %>
  <%= turbo_stream.update "new_quote_button", "" %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>Edit quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, "quotes" %>

<main class="container">

  <div class="header">
    <h1>Quotes</h1>
    <%= turbo_frame_tag "new_quote_button" do %>
      <% if @quotes.present? %>
        <%= link_to "New quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) }, class: "btn btn--primary" %>
      <% end %>
    <% end %>
  </div>


  <%= turbo_frame_tag Quote.new %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render "quotes/empty_state" %>
    <%= render partial: "quote", collection: @quotes, as: :quote %>
  <% end %>

</main>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>